// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CustomerPetColumns holds the columns for the "customer_pet" table.
	CustomerPetColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_pets", Type: field.TypeInt, Nullable: true},
	}
	// CustomerPetTable holds the schema information for the "customer_pet" table.
	CustomerPetTable = &schema.Table{
		Name:       "customer_pet",
		Columns:    CustomerPetColumns,
		PrimaryKey: []*schema.Column{CustomerPetColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "customer_pet_customer_user_pets",
				Columns:    []*schema.Column{CustomerPetColumns[1]},
				RefColumns: []*schema.Column{CustomerUserColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// CustomerUserColumns holds the columns for the "customer_user" table.
	CustomerUserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "age", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString},
	}
	// CustomerUserTable holds the schema information for the "customer_user" table.
	CustomerUserTable = &schema.Table{
		Name:       "customer_user",
		Columns:    CustomerUserColumns,
		PrimaryKey: []*schema.Column{CustomerUserColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CustomerPetTable,
		CustomerUserTable,
	}
)

func init() {
	CustomerPetTable.ForeignKeys[0].RefTable = CustomerUserTable
	CustomerPetTable.Annotation = &entsql.Annotation{
		Table: "customer_pet",
	}
	CustomerUserTable.Annotation = &entsql.Annotation{
		Table: "customer_user",
	}
}
